name: "scalafmt"
description: "Format your code with scalafmt"
inputs:
  workdir:
    description: "Working directory relative to the root directory."
    default: "."
outputs:
runs:
  using: "docker"
  image: "Dockerfile"
